#############################################################################
# Makefile for building: libSankoreAPI.a
# Generated by qmake (2.01a) (Qt 4.8.1) on: Wed Nov 21 09:40:21 2012
# Project:  SankoreAPI.pro
# Template: lib
# Command: /usr/bin/qmake -spec /usr/share/qt4/mkspecs/linux-g++ -o Makefile SankoreAPI.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_WEBKIT -DSANKOREAPI_LIBRARY -DQT_NO_DEBUG -DQT_WEBKIT_LIB -DQT_PHONON_LIB -DQT_MULTIMEDIA_LIB -DQT_TESTLIB_LIB -DQT_SVG_LIB -DQT_XMLPATTERNS_LIB -DQT_XML_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -fPIC -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -fPIC -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtNetwork -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtXml -I/usr/include/qt4/QtXmlPatterns -I/usr/include/qt4/QtSvg -I/usr/include/qt4/QtTest -I/usr/include/qt4/QtMultimedia -I/usr/include/phonon -I/usr/include/qt4/QtWebKit -I/usr/include/qt4 -I../Sankore-ThirdParty/quazip/quazip-0.3 -Iabstract -IcustomWidgets -Idevtools -Iframeworks -Iglobals -Iinterfaces -I/usr/include/qt4/phonon_compat -Ibuild/linux/release/moc
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = build/linux/release/objects/

####### Files

SOURCES       = abstract/UBAbstractMetaDataProvider.cpp \
		abstract/UBAbstractDocumentUser.cpp \
		customWidgets/UBMediaWidget.cpp \
		customWidgets/UBActionableWidget.cpp \
		customWidgets/UBDockPaletteWidget.cpp \
		frameworks/UBGeometryUtils.cpp \
		frameworks/UBPlatformUtils.cpp \
		frameworks/UBFileSystemUtils.cpp \
		frameworks/UBStringUtils.cpp \
		frameworks/UBVersion.cpp \
		frameworks/UBCryptoUtils.cpp \
		frameworks/UBBase32.cpp \
		frameworks/UBPlatformUtils_linux.cpp \
		main.cpp build/linux/release/moc/moc_UBAbstractDocumentUser.cpp \
		build/linux/release/moc/moc_UBMediaWidget.cpp \
		build/linux/release/moc/moc_UBActionableWidget.cpp \
		build/linux/release/moc/moc_UBDockPaletteWidget.cpp \
		build/linux/release/moc/moc_UBFileSystemUtils.cpp \
		build/linux/release/moc/moc_UBCryptoUtils.cpp
OBJECTS       = build/linux/release/objects/UBAbstractMetaDataProvider.o \
		build/linux/release/objects/UBAbstractDocumentUser.o \
		build/linux/release/objects/UBMediaWidget.o \
		build/linux/release/objects/UBActionableWidget.o \
		build/linux/release/objects/UBDockPaletteWidget.o \
		build/linux/release/objects/UBGeometryUtils.o \
		build/linux/release/objects/UBPlatformUtils.o \
		build/linux/release/objects/UBFileSystemUtils.o \
		build/linux/release/objects/UBStringUtils.o \
		build/linux/release/objects/UBVersion.o \
		build/linux/release/objects/UBCryptoUtils.o \
		build/linux/release/objects/UBBase32.o \
		build/linux/release/objects/UBPlatformUtils_linux.o \
		build/linux/release/objects/main.o \
		build/linux/release/objects/moc_UBAbstractDocumentUser.o \
		build/linux/release/objects/moc_UBMediaWidget.o \
		build/linux/release/objects/moc_UBActionableWidget.o \
		build/linux/release/objects/moc_UBDockPaletteWidget.o \
		build/linux/release/objects/moc_UBFileSystemUtils.o \
		build/linux/release/objects/moc_UBCryptoUtils.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_phonon.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		abstract/abstract.pri \
		customWidgets/customWidgets.pri \
		devtools/devtools.pri \
		frameworks/frameworks.pri \
		globals/globals.pri \
		interfaces/interfaces.pri \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/staticlib.prf \
		/usr/share/qt4/mkspecs/features/static.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		SankoreAPI.pro
QMAKE_TARGET  = SankoreAPI
DESTDIR       = build/linux/release/product/
TARGET        = libSankoreAPI.a

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile build/linux/release/product/$(TARGET) 

staticlib: build/linux/release/product/$(TARGET)

build/linux/release/product/$(TARGET):  $(OBJECTS) $(OBJCOMP) 
	@$(CHK_DIR_EXISTS) build/linux/release/product/ || $(MKDIR) build/linux/release/product/ 
	-$(DEL_FILE) $(TARGET)
	$(AR) $(TARGET) $(OBJECTS)
	-$(DEL_FILE) build/linux/release/product/$(TARGET)
	-$(MOVE) $(TARGET) build/linux/release/product/


Makefile: SankoreAPI.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_phonon.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		abstract/abstract.pri \
		customWidgets/customWidgets.pri \
		devtools/devtools.pri \
		frameworks/frameworks.pri \
		globals/globals.pri \
		interfaces/interfaces.pri \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/staticlib.prf \
		/usr/share/qt4/mkspecs/features/static.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/lib/i386-linux-gnu/libQtWebKit.prl \
		/usr/lib/i386-linux-gnu/libQtTest.prl \
		/usr/lib/i386-linux-gnu/libQtSvg.prl \
		/usr/lib/i386-linux-gnu/libQtXmlPatterns.prl \
		/usr/lib/i386-linux-gnu/libQtXml.prl \
		/usr/lib/i386-linux-gnu/libQtGui.prl \
		/usr/lib/i386-linux-gnu/libQtNetwork.prl \
		/usr/lib/i386-linux-gnu/libQtCore.prl
	$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ -o Makefile SankoreAPI.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_phonon.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
abstract/abstract.pri:
customWidgets/customWidgets.pri:
devtools/devtools.pri:
frameworks/frameworks.pri:
globals/globals.pri:
interfaces/interfaces.pri:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/staticlib.prf:
/usr/share/qt4/mkspecs/features/static.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/lib/i386-linux-gnu/libQtWebKit.prl:
/usr/lib/i386-linux-gnu/libQtTest.prl:
/usr/lib/i386-linux-gnu/libQtSvg.prl:
/usr/lib/i386-linux-gnu/libQtXmlPatterns.prl:
/usr/lib/i386-linux-gnu/libQtXml.prl:
/usr/lib/i386-linux-gnu/libQtGui.prl:
/usr/lib/i386-linux-gnu/libQtNetwork.prl:
/usr/lib/i386-linux-gnu/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ -o Makefile SankoreAPI.pro

dist: 
	@$(CHK_DIR_EXISTS) build/linux/release/objects/SankoreAPI1.0 || $(MKDIR) build/linux/release/objects/SankoreAPI1.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) build/linux/release/objects/SankoreAPI1.0/ && $(COPY_FILE) --parents abstract/UBAbstractMetaDataProvider.h abstract/UBAbstractDocumentUser.h customWidgets/UBMediaWidget.h customWidgets/UBActionableWidget.h customWidgets/UBDockPaletteWidget.h devtools/memcheck.h frameworks/UBGeometryUtils.h frameworks/UBPlatformUtils.h frameworks/UBFileSystemUtils.h frameworks/UBStringUtils.h frameworks/UBVersion.h frameworks/UBCryptoUtils.h frameworks/UBBase32.h globals/UBGlobals.h interfaces/IDataStorage.h interfaces/ISavable.h interfaces/IMetaDataProvider.h interfaces/IDockable.h interfaces/IDocumentUser.h interfaces/IDocument.h interfaces/IBoardUser.h SankoreAPI_global.h build/linux/release/objects/SankoreAPI1.0/ && $(COPY_FILE) --parents abstract/UBAbstractMetaDataProvider.cpp abstract/UBAbstractDocumentUser.cpp customWidgets/UBMediaWidget.cpp customWidgets/UBActionableWidget.cpp customWidgets/UBDockPaletteWidget.cpp frameworks/UBGeometryUtils.cpp frameworks/UBPlatformUtils.cpp frameworks/UBFileSystemUtils.cpp frameworks/UBStringUtils.cpp frameworks/UBVersion.cpp frameworks/UBCryptoUtils.cpp frameworks/UBBase32.cpp frameworks/UBPlatformUtils_linux.cpp main.cpp build/linux/release/objects/SankoreAPI1.0/ && (cd `dirname build/linux/release/objects/SankoreAPI1.0` && $(TAR) SankoreAPI1.0.tar SankoreAPI1.0 && $(COMPRESS) SankoreAPI1.0.tar) && $(MOVE) `dirname build/linux/release/objects/SankoreAPI1.0`/SankoreAPI1.0.tar.gz . && $(DEL_FILE) -r build/linux/release/objects/SankoreAPI1.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: build/linux/release/moc/moc_UBAbstractDocumentUser.cpp build/linux/release/moc/moc_UBMediaWidget.cpp build/linux/release/moc/moc_UBActionableWidget.cpp build/linux/release/moc/moc_UBDockPaletteWidget.cpp build/linux/release/moc/moc_UBFileSystemUtils.cpp build/linux/release/moc/moc_UBCryptoUtils.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) build/linux/release/moc/moc_UBAbstractDocumentUser.cpp build/linux/release/moc/moc_UBMediaWidget.cpp build/linux/release/moc/moc_UBActionableWidget.cpp build/linux/release/moc/moc_UBDockPaletteWidget.cpp build/linux/release/moc/moc_UBFileSystemUtils.cpp build/linux/release/moc/moc_UBCryptoUtils.cpp
build/linux/release/moc/moc_UBAbstractDocumentUser.cpp: interfaces/IDocument.h \
		SankoreAPI_global.h \
		interfaces/IDocumentUser.h \
		abstract/UBAbstractDocumentUser.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) abstract/UBAbstractDocumentUser.h -o build/linux/release/moc/moc_UBAbstractDocumentUser.cpp

build/linux/release/moc/moc_UBMediaWidget.cpp: SankoreAPI_global.h \
		customWidgets/UBActionableWidget.h \
		customWidgets/UBMediaWidget.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) customWidgets/UBMediaWidget.h -o build/linux/release/moc/moc_UBMediaWidget.cpp

build/linux/release/moc/moc_UBActionableWidget.cpp: SankoreAPI_global.h \
		customWidgets/UBActionableWidget.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) customWidgets/UBActionableWidget.h -o build/linux/release/moc/moc_UBActionableWidget.cpp

build/linux/release/moc/moc_UBDockPaletteWidget.cpp: SankoreAPI_global.h \
		customWidgets/UBDockPaletteWidget.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) customWidgets/UBDockPaletteWidget.h -o build/linux/release/moc/moc_UBDockPaletteWidget.cpp

build/linux/release/moc/moc_UBFileSystemUtils.cpp: globals/UBGlobals.h \
		SankoreAPI_global.h \
		frameworks/UBFileSystemUtils.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) frameworks/UBFileSystemUtils.h -o build/linux/release/moc/moc_UBFileSystemUtils.cpp

build/linux/release/moc/moc_UBCryptoUtils.cpp: SankoreAPI_global.h \
		frameworks/UBCryptoUtils.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) frameworks/UBCryptoUtils.h -o build/linux/release/moc/moc_UBCryptoUtils.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: build/linux/release/ui/qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) build/linux/release/ui/qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

build/linux/release/objects/UBAbstractMetaDataProvider.o: abstract/UBAbstractMetaDataProvider.cpp abstract/UBAbstractMetaDataProvider.h \
		SankoreAPI_global.h \
		interfaces/IMetaDataProvider.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/linux/release/objects/UBAbstractMetaDataProvider.o abstract/UBAbstractMetaDataProvider.cpp

build/linux/release/objects/UBAbstractDocumentUser.o: abstract/UBAbstractDocumentUser.cpp abstract/UBAbstractDocumentUser.h \
		interfaces/IDocument.h \
		SankoreAPI_global.h \
		interfaces/IDocumentUser.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/linux/release/objects/UBAbstractDocumentUser.o abstract/UBAbstractDocumentUser.cpp

build/linux/release/objects/UBMediaWidget.o: customWidgets/UBMediaWidget.cpp globals/UBGlobals.h \
		customWidgets/UBMediaWidget.h \
		SankoreAPI_global.h \
		customWidgets/UBActionableWidget.h \
		devtools/memcheck.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/linux/release/objects/UBMediaWidget.o customWidgets/UBMediaWidget.cpp

build/linux/release/objects/UBActionableWidget.o: customWidgets/UBActionableWidget.cpp customWidgets/UBActionableWidget.h \
		SankoreAPI_global.h \
		devtools/memcheck.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/linux/release/objects/UBActionableWidget.o customWidgets/UBActionableWidget.cpp

build/linux/release/objects/UBDockPaletteWidget.o: customWidgets/UBDockPaletteWidget.cpp customWidgets/UBDockPaletteWidget.h \
		SankoreAPI_global.h \
		devtools/memcheck.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/linux/release/objects/UBDockPaletteWidget.o customWidgets/UBDockPaletteWidget.cpp

build/linux/release/objects/UBGeometryUtils.o: frameworks/UBGeometryUtils.cpp frameworks/UBGeometryUtils.h \
		SankoreAPI_global.h \
		devtools/memcheck.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/linux/release/objects/UBGeometryUtils.o frameworks/UBGeometryUtils.cpp

build/linux/release/objects/UBPlatformUtils.o: frameworks/UBPlatformUtils.cpp frameworks/UBPlatformUtils.h \
		SankoreAPI_global.h \
		devtools/memcheck.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/linux/release/objects/UBPlatformUtils.o frameworks/UBPlatformUtils.cpp

build/linux/release/objects/UBFileSystemUtils.o: frameworks/UBFileSystemUtils.cpp frameworks/UBFileSystemUtils.h \
		globals/UBGlobals.h \
		SankoreAPI_global.h \
		devtools/memcheck.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/linux/release/objects/UBFileSystemUtils.o frameworks/UBFileSystemUtils.cpp

build/linux/release/objects/UBStringUtils.o: frameworks/UBStringUtils.cpp frameworks/UBStringUtils.h \
		SankoreAPI_global.h \
		devtools/memcheck.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/linux/release/objects/UBStringUtils.o frameworks/UBStringUtils.cpp

build/linux/release/objects/UBVersion.o: frameworks/UBVersion.cpp frameworks/UBVersion.h \
		SankoreAPI_global.h \
		devtools/memcheck.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/linux/release/objects/UBVersion.o frameworks/UBVersion.cpp

build/linux/release/objects/UBCryptoUtils.o: frameworks/UBCryptoUtils.cpp frameworks/UBCryptoUtils.h \
		SankoreAPI_global.h \
		devtools/memcheck.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/linux/release/objects/UBCryptoUtils.o frameworks/UBCryptoUtils.cpp

build/linux/release/objects/UBBase32.o: frameworks/UBBase32.cpp frameworks/UBBase32.h \
		SankoreAPI_global.h \
		devtools/memcheck.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/linux/release/objects/UBBase32.o frameworks/UBBase32.cpp

build/linux/release/objects/UBPlatformUtils_linux.o: frameworks/UBPlatformUtils_linux.cpp frameworks/UBPlatformUtils.h \
		SankoreAPI_global.h \
		frameworks/UBFileSystemUtils.h \
		globals/UBGlobals.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/linux/release/objects/UBPlatformUtils_linux.o frameworks/UBPlatformUtils_linux.cpp

build/linux/release/objects/main.o: main.cpp SankoreAPI_global.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/linux/release/objects/main.o main.cpp

build/linux/release/objects/moc_UBAbstractDocumentUser.o: build/linux/release/moc/moc_UBAbstractDocumentUser.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/linux/release/objects/moc_UBAbstractDocumentUser.o build/linux/release/moc/moc_UBAbstractDocumentUser.cpp

build/linux/release/objects/moc_UBMediaWidget.o: build/linux/release/moc/moc_UBMediaWidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/linux/release/objects/moc_UBMediaWidget.o build/linux/release/moc/moc_UBMediaWidget.cpp

build/linux/release/objects/moc_UBActionableWidget.o: build/linux/release/moc/moc_UBActionableWidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/linux/release/objects/moc_UBActionableWidget.o build/linux/release/moc/moc_UBActionableWidget.cpp

build/linux/release/objects/moc_UBDockPaletteWidget.o: build/linux/release/moc/moc_UBDockPaletteWidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/linux/release/objects/moc_UBDockPaletteWidget.o build/linux/release/moc/moc_UBDockPaletteWidget.cpp

build/linux/release/objects/moc_UBFileSystemUtils.o: build/linux/release/moc/moc_UBFileSystemUtils.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/linux/release/objects/moc_UBFileSystemUtils.o build/linux/release/moc/moc_UBFileSystemUtils.cpp

build/linux/release/objects/moc_UBCryptoUtils.o: build/linux/release/moc/moc_UBCryptoUtils.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/linux/release/objects/moc_UBCryptoUtils.o build/linux/release/moc/moc_UBCryptoUtils.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

